(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 728,
	height: 90,
	fps: 24,
	color: "#000000",
	opacity: 1.00,
	manifest: [
		{src:"images/_300x250_endframe_hpLogo.png?1491546726575", id:"_300x250_endframe_hpLogo"},
		{src:"images/_300x250_endframe_windows.png?1491546726575", id:"_300x250_endframe_windows"},
		{src:"images/_728x90_endframe_laptop1.jpg?1491546726575", id:"_728x90_endframe_laptop1"},
		{src:"images/_728x90_frame1_text.png?1491546726575", id:"_728x90_frame1_text"},
		{src:"images/_728x90_frame3_text.png?1491546726575", id:"_728x90_frame3_text"},
		{src:"images/_728x90_frame5_text.png?1491546726575", id:"_728x90_frame5_text"},
		{src:"images/_728x90_sprite_frame2.jpg?1491546726575", id:"_728x90_sprite_frame2"},
		{src:"images/_728x90_sprite_frame4.jpg?1491546726575", id:"_728x90_sprite_frame4"},
		{src:"images/digitaltrendslogo.png?1491546726575", id:"digitaltrendslogo"},
		{src:"images/eWeek_logo.png?1491546726575", id:"eWeek_logo"},
		{src:"images/pc_logo.png?1491546726575", id:"pc_logo"}
	]
};



lib.ssMetadata = [];


// symbols:



(lib._300x250_endframe_hpLogo = function() {
	this.initialize(img._300x250_endframe_hpLogo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,44,44);


(lib._300x250_endframe_windows = function() {
	this.initialize(img._300x250_endframe_windows);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,144,23);


(lib._728x90_endframe_laptop1 = function() {
	this.initialize(img._728x90_endframe_laptop1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib._728x90_frame1_text = function() {
	this.initialize(img._728x90_frame1_text);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,384,90);


(lib._728x90_frame3_text = function() {
	this.initialize(img._728x90_frame3_text);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,321,90);


(lib._728x90_frame5_text = function() {
	this.initialize(img._728x90_frame5_text);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,335,90);


(lib._728x90_sprite_frame2 = function() {
	this.initialize(img._728x90_sprite_frame2);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,1080);


(lib._728x90_sprite_frame4 = function() {
	this.initialize(img._728x90_sprite_frame4);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,1080);


(lib.digitaltrendslogo = function() {
	this.initialize(img.digitaltrendslogo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,184,31);


(lib.eWeek_logo = function() {
	this.initialize(img.eWeek_logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,112,31);


(lib.pc_logo = function() {
	this.initialize(img.pc_logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,53,64);


(lib.pcMaglogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.pc_logo();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,53,64);


(lib.frame6windowsLogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._300x250_endframe_windows();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,144,23);


(lib.frame6laptopbkg = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib._728x90_endframe_laptop1();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.frame6hpTitle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C9942B").s().p("ABpA7QgKgMAAgbQAAgZAKgNQAKgNAWAAQAVAAAJANQAKANAAAZQAAAbgKAMQgJANgVAAQgWAAgKgNgAB7gTQgFADgEAFQgDAFgCAGQgCAIAAAMQAAALACAJQACAIADAFQAEAFAFACQAGACAIAAQAGAAAGgCQAFgCAEgFQAEgFACgIQACgJgBgLQABgMgCgIQgCgGgEgFQgEgFgFgDQgGgCgGAAQgIAAgGACgAACA7QgIgMAAgbQAAgZAIgNQAJgNAWAAQAVAAAKANQAKANAAAZQAAAbgKAMQgKANgVAAQgWAAgJgNgAAUgTQgGADgDAFQgEAFgCAGQgBAIgBAMQABALABAJQACAIAEAFQADAFAGACQAFACAIAAQAHAAAGgCQAFgCAEgFQAEgFABgIQACgJAAgLQAAgMgCgIQgBgGgEgFQgEgFgFgDQgGgCgHAAQgIAAgFACgAKYBEQgIgDgGgIQgFgIgDgOQgDgNABgUQAAgTACgNQADgOAFgIQAGgIAJgEQAHgCALAAQAKAAAIACQAIAEAFAIQAGAIADAOQADANAAATQAAAUgDANQgDAOgGAIQgFAIgIADQgIAEgKAAQgLAAgIgEgAKbg1QgGAEgDAIQgEAHgBALQgBALgBAOQABAPABALQABALAEAIQADAHAGAEQAGADAKAAQAJAAAGgDQAGgEADgHQAEgIACgLIAAgaIAAgZQgCgLgEgHQgDgIgGgEQgGgDgJAAQgKAAgGADgAItBDQgIgEgFgKQgFgIgDgNQgCgMAAgQQAAgkAMgRQAMgSAXABIAHAAIAHABIAIABIAFABQABAAAAABQABAAAAABQABAAAAABQAAAAAAABIAAAGIgMgCIgQgBQgJAAgGACQgHADgEAHQgFAGgCAKQgDALAAAPQAFgEAIgDQAIgCALAAQAUAAAJAKQAKAIAAAVQAAAKgCAHQgCAJgFAFQgFAGgIADQgHAEgLAAQgMAAgJgFgAIxAAQgHACgHAFIAAAGQAAALACAJQABAJADAHQAFAGAFADQAHADAIAAQAPAAAHgIQAGgJAAgQIgBgMQgBgGgDgEQgDgEgFgCQgGgBgIAAQgJAAgJABgAHFBHIgJAAIgJgCIgGgBQgBAAAAgBQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgGIAOACIARABQAKAAAGgCQAHgCAEgEQAEgEABgGQACgFAAgGQAAgJgCgFQgCgFgEgDQgEgDgHgBIgMgBIgKAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgFIANAAQAIAAAGgEQAGgCADgEQADgEABgFIABgJQABgMgIgGQgGgHgQAAQgLAAgHABIgKACIgDgBIAAgCIAAgGIAOgDQAJgCAKABQAUAAAJAJQAKAKAAAQQAAALgFAIQgFAHgKAFQAMACAGAIQAFAIABAOQAAAUgNAKQgMAKgUAAIgGgBgAhPBHIgJgBIgIgCIgGgBQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAAAAAIAAgEIAAiFIAGAAIAEABQAAABAAAAQAAAAABABQAAABAAAAQAAABAAABIAAAtQAFgFAHgCQAIgDAJAAQATAAAJANQAJANAAAXQAAAPgDAKQgCAKgFAHQgFAGgIADQgIADgKAAIgKgBgAhTgSIgLAHIAABGIAKACIANABQAIAAAGgCQAGgCAEgEQAEgFACgIQABgJAAgNQAAgUgGgKQgHgKgOAAQgJAAgHADgAi2BFQgIgDgFgGQgGgGgCgKQgDgJAAgPQAAgOADgIQACgLAGgGQAEgGAIgDQAHgDAKAAQALAAAHADQAIAEADAFQAEAGACAIQABAGAAAIIAAAIIgBAHIhAAAIACARQACAHAEAFQAEAFAGACQAGACAKAAIAQgBIAIgBIADABIABACIAAAFIgNACIgRACQgLAAgIgDgAizgTQgGAEgDAEQgEAFgBAGIgCAOIA2AAIAAgCIAAgDIgBgMQgBgGgDgEQgDgEgEgCQgFgCgIAAQgIAAgFACgAj6BGQgEgBgDgDIgEgHIgBgIIAAhGIgJAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAgHIAMAAIAAgbIAIAAQABAAABABQAAAAABAAQAAABAAAAQABABAAAAIAAAYIAWAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAIAAAHIgZAAIAABFIAAAEIACAFIAEACIAIAAIAEAAIADAAIADABIABADIAAAFIgOABQgGAAgFgBgAleBCQgEgGAAgIIAAh8IAIAAQABAAABABQAAAAABAAQAAABAAAAQAAABAAABIAAB4QABAGACABQACACAFAAIAEAAIACABIABACIAAAFIgFABIgGABQgJAAgEgFgAGQBGIgCgBIgBgCIgLgVQgHgLgKgLQgLANgHALQgHAKgFAMIgGAAIgDgBQAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgCIACgDQAFgLAHgLQAIgLALgMIgJgLIgKgJIgIgOQgEgHgCgGIAKAAIACABIABACIAFAKIAHALIAIAJIAHAIQAJgJAIgKQAIgLAEgLIAGAAIADAAIAAADIAAABIgBADIgHALIgIALIgIAJIgHAJQAPAPAIAOQAIAOADAJgAEKBGQAAAAAAAAQgBAAAAAAQgBgBAAAAQgBgBAAAAQgJgMgMgMQgMgKgRgNIAAAxIgJAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAiLIAJAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAABIAABRQARgLAMgKIAUgVIAHAAQABAAAAABQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBAAAAAAQAAABAAAAIgCADIgIAIIgKAKIgNAJIgOAKIARAOIAOAMIALAOIAMAOgAkvBGQgBAAgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAAhgIAIAAQABAAABABQAAAAABAAQAAABAAAAQABABAAAAIAABggAnDBGQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiFIBIAAQABAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAAIIhAAAIAAA1IA5AAQAAAAABAAQAAAAABABQAAAAAAABQABAAAAABIAAAGIg8AAIAAA1IBAAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAIAAAIgApaBGQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiDIAIgBIAKgBIAKgBIALAAQAXAAALAKQALAKAAAYQAAANgDAIQgDAGgFAFQgGAGgHACQgIADgJAAIgOgCIgRgCIAAA2gApGg4IgLABIAAA9IAOACIAQABQAHAAAGgCQAFgBAEgEQAFgCABgHQACgGAAgKQAAgLgCgGQgDgIgEgDQgEgEgGgBIgOgBIgQABgAqEBGQgBAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIAAg/IhDAAIAABCIgIAAQgBAAAAAAQgBAAAAgBQgBAAAAgBQAAAAAAgBIAAiFIAJAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAAA8IBDAAIAAg+IAJAAQAAAAABAAQAAAAABAAQAAABAAAAQABABAAAAIAACGgAkzgyQgCgCAAgEQAAgFACgCQACgBAEAAQAFAAACABQABACAAAFQAAAEgBACQgCACgFAAQgEAAgCgCg");
	this.shape.setTransform(80.3,8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,160,30.3);


(lib.frame6hpText = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// shape
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#C8C8C8").s().p("AGuC6QgGgFAAgLIAAgpIAFAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAnIABAHIACAFQAEADAGAAIAHAAIAJgFIADgDIAAgwIAFAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAA7IgEAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgFIgHAGIgGABIgHABQgJAAgEgFgAhEC3QgGgHAAgQQAAgRAGgHQAFgIANAAQAOAAAFAIQAGAHAAARQAAAQgGAHQgFAIgOAAQgNAAgFgIgAg5CHQgDACgCADQgDADgBAFIgBAMIABAMQABAEADADQACAEADABQADABAEAAQAFAAADgBQADgBADgEIADgHIABgMIgBgMQgBgFgCgDIgGgFQgDgBgFAAQgEAAgDABgAojC3QgHgHAAgQQAAgRAHgHQAFgIANAAQANAAAGAIQAGAHAAARQAAAQgGAHQgGAIgNAAQgNAAgFgIgAoYCHQgEACgCADQgCADgCAFIAAAMIAAAMQACAEACADQACAEAEABQACABAFAAQAFAAADgBQADgBACgEIAEgHIABgMIgBgMQgCgFgCgDIgFgFQgDgBgFAAQgFAAgCABgALgC+IgEgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgEIARACIAIgBIAFgCQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAIAAgFIgBgFIgDgEIgFgCIgOgEIgGgDIgEgEQgBgDAAgEQAAgIAFgEQACgDAEgBIAJgBIAEAAIAJABIADABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgRgCIgGABIgGACIgBADIgBAEIABAFIACADIAFACIAOAEIAHADIADAFQACADAAAFQAAAEgCAEQgBADgDACQgFAEgLAAgAKsC+IgEgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIASACIAIgBIAFgCQAAAAABgBQAAAAABAAQAAgBAAAAQAAgBABAAIAAgFIgBgFIgDgEIgFgCIgOgEIgGgDIgEgEQgBgDAAgEQAAgIAFgEQACgDAEgBIAJgBIAEAAIAJABIADABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgQgCIgHABIgGACIgBADIgBAEIABAFIACADIAFACIAOAEIAGADIAFAFQABADAAAFQAAAEgBAEQgCADgDACQgGAEgKAAgAJ7C9QgFgBgDgEQgDgEgCgGQgCgGABgIQgBgJACgGQACgGADgEQADgEAEgBQAFgCAFAAQAHAAAFACQAEACACADQADAEABAEIABALIgBAIIgmAAIABALQAAAEADADQACACAEACIAKABIAJgBIAFAAIACAAIAAABIAAAEIgHABIgKABQgHAAgFgCgAKTCdIAAgMIgCgGQgCgDgDgBQgCgBgGAAQgEAAgDABQgEACgCADQgCADAAAEIgBAKIAfAAgAHyC/IgKgBIgDgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgEIARACIAIgBIAFgCQAAAAABgBQAAAAABAAQAAgBAAAAQAAgBAAAAIABgFIgBgFIgDgEIgFgCIgOgEIgGgDIgDgEQgCgDAAgEQAAgIAFgEQACgDAFgBIAJgBIACAAIAJABIAFABQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgQgCIgIABIgEACIgDADIgBAEIABAFIADADIAEACIAPAEIAGADIAFAFQABADAAAFQAAAEgBAEQgCADgDACQgGAEgJAAgAF8C/IgLgCIgDgBIgCgBIgBgCIAAhRIAFAAIACAAIAAADIAAAbQADgDAFgBQAEgCAGAAQALAAAGAIQAFAIAAAPQAAAJgCAGQgBAGgDAEQgDADgEACQgFACgHAAgAF6CIIgIAEIAAArIAHACIAIAAIAIgBQADgBACgDQADgDABgFQACgFAAgIIgBgLIgEgIQgCgDgDgCQgDgBgEAAQgFAAgEACgAEiC+IgEgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIASACIAIgBIAFgCQAAAAABgBQAAAAABAAQAAgBAAAAQAAgBAAAAIABgFIgBgFIgDgEIgFgCIgOgEIgGgDIgDgEQgCgDAAgEQAAgIAFgEQADgDAEgBIAJgBIACAAIAJABIAEABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgQgCIgIABIgFACIgCADIgBAEIABAFIADADIAEACIAPAEIAGADIAFAFQABADAAAFQAAAEgBAEQgCADgDACQgGAEgJAAgACvC+IgFgEQgDgDgBgDIgBgIQAAgFABgEIAFgGIAHgDQAEgBAGAAIAPAAIAAgFIgBgGQgBgDgBgCQgCgCgEAAIgHgBIgLABIgFAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgCIAKgCIAJgBQAHAAAEACQAEABADADQACADABADIABAIIAAAqIgEAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgFIgDADIgEACIgGACIgGABIgJgBgAC0CgIgGACQgCACAAADIAAAFQAAAHADADQADADAHAAQAGAAAFgCIAHgGIAAgTIgQAAQgEAAgDACgAB6C9QgFgBgDgEQgDgEgCgGQgCgGABgIQgBgJACgGQACgGADgEQADgEAEgBQAFgCAFAAQAHAAAFACQAEACACADQADAEABAEIABALIgBAIIgmAAIABALQAAAEADADQACACAEACIAKABIAJgBIAFAAIACAAIAAABIAAAEIgHABIgKABQgHAAgFgCgACSCdIAAgMIgCgGQgCgDgDgBQgCgBgGAAQgEAAgDABQgEACgCADQgCADAAAEIgBAKIAfAAgAj+C9QgEgCgDgFQgDgDgDgKIgBgUQAAgNABgIQACgIAEgFQADgEAEgCQAFgCAHAAQAGAAAFACQAEACAEAEQADAFACAIIACAVQAAAMgCAIIgFANIgEAEIgEADQgFACgGAAQgHAAgFgCgAj7BzQgEACgDAFQgCAEAAAHIgBAQIABAPQAAAHACAFQADAEAEACQADACAGAAQAFAAAEgCQADgCACgEQACgFACgHIAAgPIAAgQIgEgLQgCgFgDgCQgEgCgFAAQgGAAgDACgAmKC/IgKgBIgEgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIASACIAIgBIAFgCQAAAAABgBQAAAAABAAQAAgBAAAAQAAgBABAAIAAgFIgBgFIgDgEIgFgCIgOgEIgGgDIgEgEQgBgDAAgEQAAgIAFgEQACgDAEgBIAJgBIAEAAIAJABIADABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgRgCIgGABIgGACIgBADIgBAEIABAFIACADIAFACIAOAEIAGADIAEAFQACADAAAFQAAAEgCAEQgBADgDACQgFAEgLAAgApbC9QgEgDgDgEQgCgEgCgGIgBgMQAAgRAHgIQADgDAFgCQAEgCAGAAQAGAAADABIAHADIAAgcIAEAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAABVIgFAAQAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgFQgDADgFACIgFACIgGABQgHAAgDgCgApWCHQgDACgCADQgDADgBAFIgBALQAAANADAHQAEAGAJAAIAGgBIAFgCIADgCIAEgDIAAgoIgHgCIgIgBQgFAAgEABgAMRC9QAAAAAAgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAAAgBIAFgBIAEABQAAABABAAQAAABAAAAQAAABAAAAQAAABAAABQAAABAAAAQAAABAAAAQAAABAAAAQgBABAAAAIgEABQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBgAJaC+QgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgnQAAgIgEgEIgEgCIgGgBIgGABIgFACIgEACIgDADIAAAwIgFAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAg7IAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAFIAHgFIAGgCIAGgBQAFAAAEABQADABADADQACACABAEQACAEAAAGIAAApgAIcC+QgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg7IAFAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAA7gAEKC+QAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgnQAAgIgDgEIgFgCIgFgBIgGABIgGACIgEACIgCADIAAAwIgGAAQAAAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAg7IAEAAQABAAAAAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAFIAHgFIAGgCIAHgBQAFAAADABQADABADADQACACACAEQABAEAAAGIAAApgABZC+QgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgnIgBgHIgDgFIgEgCIgFgBIgGABIgFACIgEADIgDADIAAADIAAAsIgEAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAgnIAAgHIgDgFIgEgCIgFgBIgGABIgFACIgEACIgCADIAAAwIgGAAQAAAAAAAAQgBgBAAAAQAAAAAAAAQgBgBAAAAIAAg7IAFAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAAAFIADgDIAFgCIAEgCIAHgBQAGAAAEACQAEACADAFIACgDIAFgDIAGgCIAHgBQAFAAADABQADABADADQAEAFAAALIAAApgAhuC+QAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAg7IAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAHIADgDIAJgFIAGgBIACABIABABIAAAEIgDAAQgGAAgDACQgFADgEAFIAAAtgAivC+QAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAhQIAFgBIASgBQAOAAAHAGQAGAHABAOQAAAHgDAFQgBAFgDADQgDAEgFABQgFABgFAAIgTgCIAAAhgAipBxIAAAmIASACIAIgBQADgBACgCQADgCABgEIABgKIgBgLQgCgEgCgCQgCgCgEgBIgJgBgAkxC+QAAAAgBAAQAAgBAAAAQAAAAAAAAQAAgBAAAAIAAhJIgSAHIgCABQAAAAgBAAQAAAAAAgBQAAAAAAAAQgBgBAAAAIAAgDIAZgLIABAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABSgAm5C+IgCgBIgBgBIgMgtIgOAvIgFAAIgCgBIgBgBIgFgOIgLgtIAFAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABABAAIABANIALAmIAOgwIAFAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAOAuIAEgMIAJgpIAFAAIABABIAAABIgCAPIgIAeIgGAOgAp5C+QAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgnQAAgIgEgEIgEgCIgGgBIgGABIgFACIgEACIgDADIAAAwIgFAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg7IAEAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAFIAIgFIAGgCIAHgBQAEAAAEABQADABACADQADACACAEQABAEAAAGIAAApgAq4C+QAAAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg7IAFAAQAAAAABAAQAAAAAAABQAAAAAAAAQABABAAAAIAAA7gArfC+IgBgBIAAgBIgRhBIgQBDIgEAAIgCgBIgBgBIgGgVIgNg8IAGAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIADATIANA1IAQhDIAGAAIACACIAQBBIAPhJIAFAAIACAAIAAABIgNA9IgGAVgAIaB1IgCgEIACgEIADgBIAEABQAAAAABAAQAAABAAAAQAAABAAAAQABABAAABQAAAAgBABQAAABAAAAQAAAAAAABQgBAAAAABIgEABIgDgBgAq6B1IgBgEIABgEIAFgBIADABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAAAAAABQgBAAAAABIgDABIgFgBgAC+AjQgFgHgBgQQABgPAFgHQAGgIANAAQANAAAGAIQAFAHABAPQgBAQgFAHQgGAIgNAAQgNAAgGgIgADJgLQgDACgCADQgDADgBADIgBAMIABAMQABAEADADQACAEADABQADABAFAAQAEAAAEgBQADgBADgEIADgHIAAgMIAAgMQgBgDgCgDIgGgFQgEgBgEAAQgFAAgDABgAjxAmQgGgFAAgLIAAgnIAFAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAlIABAHIACAFQAFADAFAAIAHAAIAJgFIADgDIAAguIAFAAQABAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAA5IgEAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAgFIgIAGIgGABIgHABQgIAAgFgFgAnmAmQgGgFAAgLIAAgnIAFAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAlIABAHIACAFQAEADAGAAIAHAAIAJgFIADgDIAAguIAFAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAA5IgEAAQgBAAAAAAQgBAAAAgBQAAAAAAAAQgBgBAAAAIAAgFIgHAGIgGABIgHABQgJAAgEgFgAJxApQgFgBgDgEQgEgEgBgGQgBgGAAgIQAAgJABgEQABgGAEgEQADgEAEgBQAFgCAFAAQAHAAAFACQAEACACADQADAEABAEIABAJIgBAIIgnAAIACALQABAEACADQACACAEACIAKABIAJgBIAFAAIABAAIABABIAAAEIgHABIgKABQgHAAgFgCgAKJAJIAAgKIgCgGIgFgEQgCgBgGAAQgEAAgEABQgDACgCADQgCADAAADIgCAJIAgAAgAIbArIgKgCIgEgBIgBgBIgBgCIAAhPIAEAAIACAAIABADIAAAbQADgDAFgBQAEgCAGAAQALAAAFAIQAFAIAAANQABAJgCAGQgBAGgEAEQgDADgEACQgFACgHAAgAIZgKIgHAEIAAApIAGACIAIAAIAIgBQAEgBACgDQADgDAAgFQACgFAAgIIgBgLIgDgGQgCgDgEgCQgDgBgDAAQgGAAgEACgAHYAqIgEgDIgCgEIgBgFIAAgpIgFAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBIAAgEIAHAAIAAgQIAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAOIAOAAQAAAAABAAQAAABAAAAQABAAAAAAQAAABAAAAIAAAEIgQAAIAAAsIACACIADABIAJABIACAAIAAABIAAAEIgIABIgHgBgAF4ApQgFgBgDgEQgDgEgCgGQgBgGgBgIQABgJABgEQACgGADgEQADgEAFgBQAEgCAGAAQAHAAAEACQAEACACADQACAEABAEIABAJIgBAIIglAAIABALQABAEACADQACACAEACIAJABIAKgBIAFAAIACAAIAAABIAAAEIgIABIgJABQgHAAgFgCgAGQAJIAAgKIgCgGIgEgEQgEgBgEAAQgGAAgCABQgEACgCADQgCADAAADIgBAJIAfAAgACTApQgEgDgDgEIgEgJIgBgNQAAgPAGgHQADgEAEgCQAEgCAGAAIAFAAIAHABIACABQAAAAABABQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAEIgOgCIgHABQgEACgCADQgCACgBAEIgBALIABANIADAIQADADAEABIAHABIAHgBIAFAAIABAAIABABIAAAEIgIABIgIABQgGAAgFgCgABJArIgKgBIgEgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIASACIAIgBIAFgCQAAAAABgBQAAAAABAAQAAgBAAAAQAAgBABAAIAAgFIgBgFIgDgEIgFgCIgOgEIgGgDIgEgEQgBgDAAgCQAAgIAFgEQACgDAEgBIAJgBIAEAAIAJABIADABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgQgCIgHABIgGACIgBADIgBAEIABADIACADIAFACIAOAEIAGADIAFAFQABADAAAFQAAAEgBAEQgCADgDACQgGAEgKAAgAAUArIgKgBIgDgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQgBAAAAAAIAAgEIASACIAIgBIAFgCQAAAAABgBQAAAAABAAQAAgBAAAAQAAgBAAAAIABgFIgBgFIgDgEIgFgCIgOgEIgGgDIgDgEQgCgDAAgCQAAgIAFgEQADgDAEgBIAJgBIACAAIAJABIAEABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgQgCIgHABIgGACIgCADIgBAEIABADIADADIAFACIAOAEIAGADIAFAFQABADAAAFQAAAEgBAEQgCADgDACQgGAEgJAAgAgkApQgFgBgDgEQgDgEgCgGQgBgGgBgIQABgJABgEQACgGADgEQADgEAFgBQAEgCAGAAQAHAAAEACQAEACACADQACAEABAEIABAJIgBAIIglAAIABALQABAEACADQACACAEACIAKABIAJgBIAFAAIACAAIAAABIAAAEIgIABIgJABQgHAAgFgCgAgMAJIAAgKIgCgGIgEgEQgEgBgEAAQgGAAgCABQgEACgCADQgCADAAADIgBAJIAfAAgAitArIgKgBIgDgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgEIARACIAIgBIAFgCQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIABgFIgBgFIgDgEIgFgCIgOgEIgGgDIgDgEQgCgDAAgCQAAgIAFgEQADgDADgBIAJgBIADAAIAJABIAFABQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgRgCIgHABIgEACIgCADIgCAEIACADIACADIAEACIAPAEIAHADIADAFQACADAAAFQAAAEgCAEQgBADgDACQgFAEgKAAgAkkArIgKgCIgDgBIgCgBIgBgCIAAhPIAFAAIABAAIABADIAAAbQADgDAFgBQAEgCAGAAQALAAAFAIQAGAIAAANQAAAJgCAGQgBAGgDAEQgDADgFACQgEACgHAAgAkmgKIgHAEIAAApIAHACIAIAAIAIgBQADgBACgDQADgDABgFQABgFABgIIgBgLIgEgGQgCgDgDgCQgDgBgEAAQgGAAgEACgAl6ApQgFgBgDgEQgDgEgCgGQgBgGgBgIQABgJABgEQACgGADgEQADgEAFgBQAEgCAGAAQAHAAAEACQAEACACADQACAEABAEIABAJIgBAIIglAAIABALQABAEACADQACACAEACIAKABIAJgBIAFAAIACAAIAAABIAAAEIgIABIgJABQgHAAgFgCgAliAJIAAgKIgCgGIgEgEQgEgBgEAAQgGAAgCABQgEACgCADQgCADAAADIgBAJIAfAAgAoSApQgEgDgDgEIgFgJIgBgNQABgPAGgHQACgEAFgCQAEgCAGAAIAEAAIAHABIACABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgPgCIgHABQgDACgCADQgDACgBAEIgBALIABANIAEAIQADADADABIAHABIAIgBIAEAAIACAAIABABIAAAEIgIABIgIABQgGAAgFgCgApLApQgEgBgDgEQgEgEgCgGQgBgGAAgIQAAgJABgEQACgGAEgEQADgEAEgBQAFgCAFAAQAHAAAEACQAFACABADQADAEABAEIABAJIgBAIIgmAAIABALQABAEACADQACACAFACIAJABIAKgBIAEAAIACAAIABABIAAAEIgIABIgKABQgGAAgGgCgAoyAJIgBgKIgBgGIgFgEQgDgBgFAAQgFAAgDABQgDACgDADQgCADAAADIgBAJIAgAAgAp+ArIgKgBIgEgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAgBAAIAAgEIASACIAIgBIAFgCQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAIAAgFIgBgFIgDgEIgFgCIgOgEIgGgDIgEgEQgBgDAAgCQAAgIAFgEQACgDAEgBIAJgBIAEAAIAJABIADABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgRgCIgGABIgFACIgCADIgBAEIABADIACADIAFACIAOAEIAHADIADAFQACADAAAFQAAAEgCAEQgBADgDACQgFAEgLAAgAJKAnQgCgDAAgFIAAhJIAFAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAAAIAABIQAAAEACABIADAAIADAAIACABIAAABIAAADIgHABQgFAAgDgDgAH2AqQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAg5IAFAAQAAAAABAAQAAABAAAAQAAAAAAAAQAAABAAAAIAAA5gAGoAqQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAg5IAEAAQABAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAAHIAEgDIAJgFIAFgBIADABIABABIAAAEIgEAAQgFAAgEACQgEADgFAFIAAArgAFGAqIgBgBIgBgBIgRgqIgDgPIAFAAQABAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAQACAOAFAMQAEANAGALIAGgMIAJgZIACgPIAGAAIABABIAAABIgDAPIgFANIgMAdgAEhAqQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgnQAAgGgEgEIgEgCIgGgBIgGABIgFACIgEACIgDADIAAAuIgFAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAg5IAFAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAFIAIgFIAGgCIAGgBQAFAAADABQAEABADADQACACABAEQACAEAAAEIAAApgAhFAqQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgnQAAgGgEgEIgEgCIgGgBIgGABIgFACIgEACIgDADIAAAuIgFAAQgBAAAAAAQAAAAAAgBQgBAAAAAAQAAgBAAAAIAAg5IAFAAQAAAAAAAAQABABAAAAQAAAAAAAAQAAABAAAAIAAAFIAIgFIAGgCIAGgBQAFAAADABQAEABADADQACACABAEQACAEAAAEIAAApgAiEAqQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAg5IAFAAQAAAAABAAQAAABAAAAQAAAAAAAAQABABAAAAIAAA5gAmtAqQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAIAAg5IAEAAQABAAAAAAQAAABABAAQAAAAAAAAQAAABAAAAIAAAHIAEgDIAJgFIAGgBIACABIABABIAAAEIgDAAQgGAAgEACQgEADgEAFIAAArgAHzgdIgBgEIABgEIAFgBIADABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAABAAAAQAAABAAAAQgBAAAAABIgDABIgFgBgAiFgdIgBgEIABgEIADgBIAEABQAAAAABAAQAAABAAAAQAAABAAAAQABABAAABQAAAAgBABQAAABAAAAQAAABAAAAQgBAAAAABIgEABIgDgBgAJJhvQgGgHAAgQQAAgRAGgHQAGgIANAAQANAAAFAIQAGAHAAARQAAAQgGAHQgFAIgNAAQgNAAgGgIgAJUifQgDACgDADQgCADgBAFIgBAMIABAMQABAEACADQADAEADABQADABAFAAQAEAAAEgBQADgBACgEIADgHIABgMIgBgMQgBgFgCgDIgFgFQgEgBgEAAQgFAAgDABgAmlhvQgHgHAAgQQAAgRAHgHQAFgIANAAQANAAAGAIQAGAHAAARQAAAQgGAHQgGAIgNAAQgNAAgFgIgAmaifQgEACgCADQgCADgCAFIAAAMIAAAMQACAEACADQACAEAEABQACABAFAAQAFAAADgBQADgBACgEIAEgHIABgMIgBgMQgCgFgCgDIgFgFQgDgBgFAAQgFAAgCABgALBhoIgEgDIgCgEIgBgFIAAgrIgFAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgEIAHAAIAAgQIAFAAQAAAAABAAQAAAAABABQAAAAAAAAQAAAAAAABIAAAOIAOAAQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAEIgQAAIAAAuIABACIADABIAJABIACAAIABABIAAAEIgJABIgHgBgAKGhoIgEgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgEIARACIAIgBIAFgCQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBABAAIAAgFIgBgFIgDgEIgFgCIgOgEIgGgDIgEgEQgBgDAAgEQAAgIAFgEQACgDAEgBIAJgBIAEAAIAJABIADABQABAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgRgCIgGABIgGACIgBADIgBAEIABAFIACADIAFACIAOAEIAHADIADAFQACADAAAFQAAAEgCAEQgBADgDACQgFAEgLAAgAGXhpQgDgDgDgEQgCgEgCgGIAAgMQAAgRAGgIQADgDAEgCQAFgCAGAAQAGAAAEABIAFADIAAgcIAFAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAABVIgEAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIgBgFQgDADgEACIgFACIgHABQgGAAgEgCgAGeifQgEACgDADQgBADgBAFIgBALQAAANACAHQAEAGAJAAIAGgBIAFgCIADgCIADgDIAAgoIgGgCIgIgBQgFAAgDABgAEfhoIgGgEQgDgDAAgDIgBgIQAAgFABgEIAEgGIAIgDQADgBAGAAIAQAAIAAgFIgBgGQgBgDgCgCQgCgCgDAAIgIgBIgKABIgGAAQAAAAgBAAQAAAAAAAAQAAAAAAgBQAAAAgBgBIAAgCIAKgCIAJgBQAHAAAEACQAEABADADQACADABADIACAIIAAAqIgFAAQAAAAgBAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgFIgEADIgEACIgGACIgFABIgJgBgAEjiGIgFACQgCACgBADIAAAFQAAAHAEADQADADAHAAQAFAAAFgCIAIgGIAAgTIgRAAQgEAAgDACgADihoIgEgDIgCgEIgBgFIAAgrIgFAAQgBAAAAAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgEIAHAAIAAgQIAFAAQAAAAABAAQAAAAAAABQABAAAAAAQAAAAAAABIAAAOIANAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAEIgQAAIAAAuIABACIADABIAJABIACAAIABABIAAAEIgJABIgHgBgACmhoIgDgBQAAAAgBgBQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgEIARACIAIgBIAFgCQABAAAAgBQAAAAABAAQAAgBAAAAQAAgBAAAAIABgFIgBgFIgDgEIgFgCIgOgEIgGgDIgDgEQgCgDAAgEQAAgIAFgEQADgDADgBIAJgBIADAAIAJABIAFABQAAAAAAABQAAAAABAAQAAAAAAABQAAAAAAAAIAAAEIgRgCIgHABIgEACIgCADIgCAEIACAFIACADIAEACIAPAEIAHADIADAFQACADAAAFQAAAEgCAEQgBADgDACQgFAEgKAAgAB2hpQgFgBgDgEQgEgEgBgGQgCgGAAgIQAAgJACgGQABgGAEgEQADgEAFgBQAEgCAFAAQAIAAADACQAFACACADQADAEAAAEIABALIgBAIIgmAAIABALQABAEADADQACACAEACIAJABIAKgBIAFAAIABAAIABABIAAAEIgIABIgKABQgGAAgFgCgACPiJIgBgMIgCgGIgEgEQgEgBgFAAQgEAAgEABQgDACgCADQgCADgBAEIgBAKIAhAAgAh/hoIgFgDIgBgEIgBgFIAAgrIgGAAQAAAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAgBIAAgEIAHAAIAAgQIAEAAQABAAAAAAQABAAAAABQAAAAAAAAQAAAAAAABIAAAOIAOAAQAAAAABAAQAAAAABABQAAAAAAAAQAAABAAAAIAAAEIgQAAIAAAuIACACIADABIAJABIABAAIABABIAAAEIgJABIgGgBgAjUhoIgDgBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgEIARACIAIgBIAGgCQAAAAAAgBQABAAAAAAQAAgBABAAQAAgBAAAAIAAgFIgBgFIgCgEIgGgCIgNgEIgHgDIgDgEQgCgDAAgEQABgIAEgEQADgDAEgBIAJgBIADAAIAJABIAEABQAAAAABABQAAAAAAAAQAAAAAAABQABAAAAAAIAAAEIgRgCIgHABIgFACIgCADIgBAEIABAFIADADIAEACIAPAEIAGADIAEAFQABADAAAFQAAAEgBAEQgBADgEACQgFAEgKAAgAkfhpQgEgDgDgEQgCgEgBgGIgBgMQAAgRAGgIQADgDAFgCQAFgCAFAAQAHAAADABIAGADIAAgcIAEAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAAAIAABVIgFAAQAAAAgBAAQAAgBAAAAQAAAAAAAAQAAgBgBAAIAAgFQgDADgFACIgEACIgHABQgGAAgEgCgAkZifQgDACgDADQgCADgBAFIgBALQAAANADAHQADAGAKAAIAGgBIAEgCIAEgCIADgDIAAgoIgHgCIgIgBQgFAAgDABgApDhpQgFgBgDgEQgEgEgBgGQgBgGAAgIQAAgJABgGQABgGAEgEQADgEAEgBQAFgCAFAAQAHAAAFACQAEACACADQADAEABAEIABALIgBAIIgnAAIACALQABAEACADQACACAEACIAKABIAJgBIAFAAIABAAIABABIAAAEIgHABIgKABQgHAAgFgCgAoriJIAAgMIgCgGIgFgEQgCgBgGAAQgEAAgEABQgDACgCADQgCADAAAEIgCAKIAgAAgAlChrQgCgDAAgFIAAhLIAEAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAABKQAAAEACABIAEAAIACAAIACABIAAABIAAADIgGABQgFAAgDgDgAIwhoQAAAAgBAAQAAgBAAAAQAAAAAAAAQAAgBAAAAIAAgnIgBgHIgDgFIgEgCIgGgBIgFABIgGACIgDADIgEADIABADIAAAsIgFAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgnIAAgHIgEgFIgDgCIgGgBIgFABIgGACIgDACIgDADIAAAwIgFAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg7IAEAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAFIAEgDIAEgCIAFgCIAGgBQAGAAAFACQAEACACAFIADgDIAEgDIAHgCIAHgBQAEAAADABQADABADADQAFAFAAALIAAApgAF6hoQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAgnQAAgIgEgEIgEgCIgGgBIgGABIgFACIgEACIgDADIAAAwIgFAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAg7IAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAFIAIgFIAGgCIAGgBQAFAAADABQAEABADADQACACABAEQACAEAAAGIAAApgABVhoQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgnQAAgIgEgEIgEgCIgGgBIgGABIgFACIgEACIgDADIAAAwIgFAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg7IAEAAQABAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIAAAFIAIgFIAGgCIAHgBQAEAAAEABQADABACADQADACACAEQABAEAAAGIAAApgAAYhoQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgnQAAgIgEgEIgEgCIgGgBIgGABIgDACIgEACIgDADIAAAwIgFAAQAAAAgBAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg7IAEAAQABAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAFIAHgFIAEgCIAHgBQAEAAAEABQADABACADQADACACAEQABAEAAAGIAAApgAgkhoQgBAAAAAAQAAgBgBAAQAAAAAAAAQAAgBAAAAIAAg7IAFAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAABAAAAIAAA7gAg7hoQAAAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAgnQAAgIgFgEIgDgCIgHgBIgFABIgGACIgDACIgEADIAAAwIgEAAQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAIAAhUIAEAAQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAAAIAAAfQADgDAFgDIAGgBIAGgBQAEAAAEABQADABADADQADACABAEQACAEAAAGIAAApgAlqhoQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAg7IAFAAQAAAAAAAAQABAAAAABQAAAAAAAAQABABAAAAIAAAHIADgDIAJgFIAGgBIACABIABABIAAAEIgDAAQgGAAgDACQgFADgEAFIAAAtgAnLhoIgCgBIgBgBIgNgtIgOAvIgFAAIgBgBIgCgBIgKgdIgFgeIAFAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAIAEAaIAJAZIANgwIAGAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAABIAOAuIAMg1IAFAAIACABIAAABIgLAtIgGAOgApkhoQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAgnQAAgIgEgEIgEgCIgGgBIgGABIgFACIgEACIgDADIAAAwIgFAAQAAAAgBAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAhUIAFAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAIAAAfQADgDAFgDIAFgBIAHgBQAEAAAEABQADABADADQACACABAEQACAEAAAGIAAApgAq1hoQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAAhLIgWAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAgBIAAgEIA0AAQAAAAABAAQAAAAAAAAQAAAAAAABQABAAAAAAIAAAFIgYAAIAABNgAjqijQAAAAgBAAQAAAAAAgBQAAAAgBAAQAAAAAAgBIgBgWIAGAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIAAAXgAgnixIgBgEIABgEIAFgBIADABQAAAAABAAQAAABAAAAQAAABAAAAQAAABAAABQAAAAAAABQAAAAAAABQAAAAAAABQgBAAAAABIgDABIgFgBg");
	this.shape.setTransform(79.9,14.6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-4,-4.6,168.1,50);


(lib.frame6hpLogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._300x250_endframe_hpLogo();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,44,44);


(lib.frame6cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// text shape
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AguA5QgBAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAhNIgCAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIAAgDIAGgBIAFAAIAHgBIAGAAQAHAAAGACQAGABADAEQAEAEADAGQAAAGAAAIQAAAIAAAGQgBAHgDAEQgDAFgFACQgFACgIAAQgGAAgEgBIgGgDIAAAZgAgpgWIAAAwIAHADIAIABIAJgBQAEgCACgDQACgDACgFIABgOIgBgKQgCgFgCgEQgDgDgEgBQgFgCgGAAIgGAAIgGABgAByAcQgGgIgBgSQABgPAGgIQAGgJAOAAQAOAAAGAJQAHAIAAAPQAAASgHAIQgGAJgOAAQgOAAgGgJgAB+gWQgEACgCADQgCADgCAGIgBAKIABAOQACAFACADQACADAEACQAEABAEAAQAFAAAEgBQADgCADgDQACgDABgFIABgOIgBgKQgBgGgCgDQgDgDgDgCQgEgBgFAAQgEAAgEABgAhwAcQgHgIABgSQgBgPAHgIQAGgJAOAAQAOAAAHAJQAFAIABAPQgBASgFAIQgHAJgOAAQgOAAgGgJgAhkgWQgEACgCADQgDADgBAGIgBAKIABAOQABAFADADQACADAEACQADABAFAAQAFAAAEgBQADgCACgDQADgDABgFIABgOIgBgKQgBgGgDgDQgCgDgDgCQgEgBgFAAQgFAAgDABgAjwAkIgJgDQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIAAgEIAKACIAOABQAFAAAFgCQAEgBACgCQADgDABgDIABgHIgBgIQgBgDgDgBIgHgCIgLgEIgJgDIgHgFQgDgDgCgEQgCgEAAgGQAAgFABgEQACgFAEgCQADgDAFgCQAFgCAIAAIAFAAIAFABIAGAAIADABQABAAAAABQABAAAAAAQAAABAAAAQAAABAAAAIAAAEIgKgBIgLgBQgLAAgFAEQgEAEAAAIIABAHQABADACACIAHADIAJADIALAEQAFACADADQADADACACQABAEAAAHQAAAMgGAGQgIAGgOAAIgNAAgADmAjIgCAAIgBgCIgOgvIgPAxIgGAAIgCAAIgBgCIgFgPIgFgQIgEgPIgDgPIAHAAQAAAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIACANIAEANIADAOIAFANIAPgyIAGAAQAAAAABAAQAAAAAAAAQABABAAAAQAAAAAAABIAPAwIAEgNIAFgOIADgOIACgOIAFAAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABIABABIgDAPIgEAPIgFAQIgGAPgABXAjQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgoQAAgJgEgDQgEgEgHAAIgHABIgFACIgEADIgEADIAAAxIgFAAQAAAAgBAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAg9IAEAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABIAAAFIADgDIAFgDIAGgCIAHgBQAKAAAGAGQAFAFAAAMIAAAqgAiLAjQAAAAgBAAQAAAAAAAAQgBAAAAgBQAAAAAAgBIAAgoQAAgJgEgDQgEgEgHAAIgGABIgGACIgEADIgEADIAAAxIgFAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhZIAFAAQABAAAAAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAhIAIgGQAGgDAIAAQAJAAAFAGQAHAFgBAMIAAAqg");
	this.shape.setTransform(40.1,13.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// bkg shape
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#C9942B").s().rr(-40,-12.5,80,25,5);
	this.shape_1.setTransform(40,12.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,80,25);


(lib.frame5txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib._728x90_frame5_text();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-15,0,360,90);


(lib.frame4sprite = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._728x90_sprite_frame4();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2).to({y:-90},0).wait(2).to({y:-180},0).wait(2).to({y:-270},0).wait(2).to({y:-360},0).wait(2).to({y:-450},0).wait(2).to({y:-540},0).wait(2).to({y:-630},0).wait(2).to({y:-720},0).wait(2).to({y:-810},0).wait(2).to({y:-900},0).wait(2).to({y:-990},0).wait(13).to({y:-900},0).wait(1).to({y:-810},0).wait(1).to({y:-720},0).wait(1).to({y:-630},0).wait(1).to({y:-540},0).wait(1).to({y:-450},0).wait(1).to({y:-360},0).wait(1).to({y:-270},0).wait(1).to({y:-180},0).wait(1).to({y:-90},0).wait(1).to({y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,728,1080);


(lib.frame3txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib._728x90_frame3_text();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-5,0,330,90);


(lib.frame2sprite = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib._728x90_sprite_frame2();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2).to({y:-90},0).wait(2).to({y:-180},0).wait(2).to({y:-270},0).wait(2).to({y:-360},0).wait(2).to({y:-450},0).wait(2).to({y:-540},0).wait(2).to({y:-630},0).wait(2).to({y:-720},0).wait(2).to({y:-810},0).wait(2).to({y:-900},0).wait(2).to({y:-990},0).wait(13).to({y:-900},0).wait(1).to({y:-810},0).wait(1).to({y:-720},0).wait(1).to({y:-630},0).wait(1).to({y:-540},0).wait(1).to({y:-450},0).wait(1).to({y:-360},0).wait(1).to({y:-270},0).wait(1).to({y:-180},0).wait(1).to({y:-90},0).wait(1).to({y:0},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,728,1080);


(lib.frame1txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.instance = new lib._728x90_frame1_text();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-8,0,400,90);


(lib.eWeeklogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.eWeek_logo();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,112,31);


(lib.digitalTrendsLogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.digitaltrendslogo();

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,184,31);


// stage content:
(lib._31266_hp_ww_elitebook_oldman_microsoft_728x90 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// frame1-txt
	this.instance = new lib.frame1txt();
	this.instance.setTransform(308.1,26,1.15,1.15,0,0,0,200.1,25.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:200.5,regY:26,scaleX:1,scaleY:1,x:301.1,alpha:1},23).wait(24).to({alpha:0},12).to({_off:true},1).wait(268));

	// pcMag-logo
	this.instance_1 = new lib.pcMaglogo();
	this.instance_1.setTransform(617.5,44.8,1.151,1.151,0,0,0,26.5,32);
	this.instance_1.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({scaleX:0.84,scaleY:0.84,x:617.4,y:44,alpha:1},23).wait(24).to({alpha:0},12).to({_off:true},1).wait(268));

	// frame2-sprite
	this.instance_2 = new lib.frame2sprite("synched",0,false);
	this.instance_2.setTransform(1800,125,1,1,0,0,0,1800,125);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(56).to({_off:false},0).wait(34).to({startPosition:34},0).to({alpha:0,mode:"single",startPosition:45},11).to({_off:true},1).wait(226));

	// frame3-txt
	this.instance_3 = new lib.frame3txt();
	this.instance_3.setTransform(257.9,24.1,1.149,1.148,0,0,0,165.2,25.3);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(99).to({_off:false},0).to({regX:165,regY:26,scaleX:1,scaleY:1,x:255,y:26,alpha:1},24).wait(24).to({alpha:0},24).to({_off:true},1).wait(156));

	// digital-trends-logo
	this.instance_4 = new lib.digitalTrendsLogo();
	this.instance_4.setTransform(556.5,45,1.147,1.145,0,0,0,92,15.5);
	this.instance_4.alpha = 0;
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(99).to({_off:false},0).to({scaleX:1,scaleY:1,x:558,alpha:1},24).wait(24).to({alpha:0},24).to({_off:true},1).wait(156));

	// frame4-sprite
	this.instance_5 = new lib.frame4sprite("synched",0,false);
	this.instance_5.setTransform(1800,300,1,1,0,0,0,1800,300);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(168).to({_off:false},0).wait(34).to({startPosition:34},0).to({alpha:0,mode:"single",startPosition:45},11).to({_off:true},1).wait(114));

	// frame5-txt
	this.instance_6 = new lib.frame5txt();
	this.instance_6.setTransform(278.1,45.1,1.149,1.148,0,0,0,181,46.2);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(211).to({_off:false},0).to({regY:46,scaleX:1,scaleY:1,x:273,y:46,alpha:1},24).wait(45).to({alpha:0},24).to({_off:true},1).wait(23));

	// eWeek logo
	this.instance_7 = new lib.eWeeklogo();
	this.instance_7.setTransform(522,45.3,1.202,1.2,0,0,0,56,15.8);
	this.instance_7.alpha = 0;
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(211).to({_off:false},0).to({regY:16,scaleX:1,scaleY:1,y:46,alpha:1},24).wait(45).to({alpha:0},24).to({_off:true},1).wait(23));

	// HP Logo
	this.instance_8 = new lib.frame6hpLogo();
	this.instance_8.setTransform(48,45.1,1.2,1.2,0,0,0,22.1,22.1);
	this.instance_8.alpha = 0;
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(305).to({_off:false},0).to({regX:22,regY:22,scaleX:1,scaleY:1,y:45,alpha:1},9).wait(14));

	// HP Title
	this.instance_9 = new lib.frame6hpTitle();
	this.instance_9.setTransform(341.1,26.8,1.2,1.2,0,0,0,80.1,14.8);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(309).to({_off:false},0).to({regX:80,regY:15,scaleX:1,scaleY:1,x:341,y:27,alpha:1},8).wait(11));

	// HP Text
	this.instance_10 = new lib.frame6hpText();
	this.instance_10.setTransform(341.1,58.8,1.2,1.2,0,0,0,80.1,16.5);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(313).to({_off:false},0).to({regX:80,regY:17,scaleX:1,scaleY:1,x:341,y:59,alpha:1},8).wait(7));

	// CTA
	this.instance_11 = new lib.frame6cta();
	this.instance_11.setTransform(497.7,46.3,1.2,1.2,0,0,0,43.1,13.6);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(317).to({_off:false},0).to({regX:43,regY:13.5,scaleX:1,scaleY:1,x:498,y:46.5,alpha:1},7).wait(4));

	// Windows Logo
	this.instance_12 = new lib.frame6windowsLogo();
	this.instance_12.setTransform(635.5,44.9,1.2,1.2,0,0,0,72.1,11.6);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(320).to({_off:false},0).to({regX:72,regY:11.5,scaleX:1,scaleY:1,x:636,y:45.5,alpha:1},7).wait(1));

	// bkg
	this.instance_13 = new lib.frame6laptopbkg();
	this.instance_13.setTransform(364.3,45,1.2,1.2,0,0,0,364.2,45);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(301).to({_off:false},0).to({regX:364,scaleX:1,scaleY:1,x:364,alpha:1},10).wait(17));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(442,42,570,103.5);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;