(function($,Drupal){Drupal.behaviors.exampleBehavior={attach:function(context,settings){$(window).load(function(){jQuery('form input.form-email').val("");jQuery('form input.form-text').val("");});$(".js-form-item-name .form-text ").focus(function(){$(this).parent().addClass("input--filled-newclass");});$(".js-form-item-name .form-text").change(function(){$(this).parent().toggleClass("input--filled-new");});$(".js-form-item-name .form-text").blur(function(){$(this).parent().removeClass("input--filled-newclass");});$(".js-form-item-mail .form-email ").focus(function(){$(this).parent().addClass("input--filled-newclass");});$(".js-form-item-mail .form-email").change(function(){$(this).parent().toggleClass("input--filled-new");});$(".js-form-item-mail .form-email").blur(function(){$(this).parent().removeClass("input--filled-newclass");});$(".js-form-item-field-telephone-0-value .form-tel ").focus(function(){$(this).parent().addClass("input--filled-newclass");});$(".js-form-item-field-telephone-0-value .form-tel").change(function(){$(this).parent().toggleClass("input--filled-new");});$(".js-form-item-field-telephone-0-value .form-tel").blur(function(){$(this).parent().removeClass("input--filled-newclass");});$(".js-form-item-field-company-organisation-0-value .form-text ").focus(function(){$(this).parent().addClass("input--filled-newclass");});$(".js-form-item-field-company-organisation-0-value .form-text").change(function(){$(this).parent().toggleClass("input--filled-new");});$(".js-form-item-field-company-organisation-0-value .form-text").blur(function(){$(this).parent().removeClass("input--filled-newclass");});$(".js-form-item-message-0-value .form-textarea ").focus(function(){$(this).parent().addClass("input--filled-newclass");});$(".js-form-item-message-0-value .form-textarea").change(function(){$(this).parent().toggleClass("input--filled-new");});$(".js-form-item-message-0-value .form-textarea").blur(function(){$(this).parent().removeClass("input--filled-newclass");});mainSlider1();mainSlider2();mainSlider3();function mainSlider1(){$('.image-sliders').slick({infinite:true,slidesToShow:1,slidesToScroll:1,dots:true,autoplay:true,autoplaySpeed:3000,arrows:false,speed:300,responsive:[{breakpoint:1200,settings:{slidesToShow:4,slidesToScroll:2}},{breakpoint:900,settings:{slidesToShow:3,slidesToScroll:3}},{breakpoint:800,settings:{slidesToShow:3,slidesToScroll:3}}]});}
function mainSlider3(){$('.single-image-slider').slick({infinite:true,slidesToShow:1,slidesToScroll:1,dots:true,autoplay:true,autoplaySpeed:3000,arrows:false,speed:300,responsive:[{breakpoint:1200,settings:{slidesToShow:1,slidesToScroll:2}},{breakpoint:900,settings:{slidesToShow:1,slidesToScroll:1}},{breakpoint:800,settings:{slidesToShow:1,slidesToScroll:1}}]});}
function mainSlider2(){$('.logo-carousel').slick({infinite:false,slidesToShow:5,slidesToScroll:5,dots:true,autoplay:true,autoplaySpeed:3000,arrows:false,speed:300,responsive:[{breakpoint:1200,settings:{slidesToShow:5,slidesToScroll:5}},{breakpoint:900,settings:{slidesToShow:2,slidesToScroll:2}},{breakpoint:800,settings:{slidesToShow:2,slidesToScroll:2}}]});}
jQuery("#sticky-scroll-box").stick_in_parent();jQuery("#block-simplenewssubscription #edit-mail-0-value").attr("placeholder","..type in your e-mail id");jQuery('.body.field.field-node--body').articleProgress({target:'.ap-width>div'});jQuery('.body.field.field-node--body').articleProgress({target:'.ap-text',mode:'text'});$.fn.parallax=function(){var window_width=$(window).width();return this.each(function(i){var $this=$(this);$this.addClass('parallax');function updateParallax(initial){var container_height;if(window_width<601){container_height=($this.height()>0)?$this.height():$this.children("img").height();}
else{container_height=($this.height()>0)?$this.height():500;}
var $img=$this.children("img").first();var img_height=$img.height();var parallax_dist=img_height-container_height;var bottom=$this.offset().top+container_height;var top=$this.offset().top;var scrollTop=$(window).scrollTop();var windowHeight=window.innerHeight;var windowBottom=scrollTop+windowHeight;var percentScrolled=(windowBottom-top)/(container_height+windowHeight);var parallax=Math.round((parallax_dist*percentScrolled));if(initial){$img.css('display','block');}
if((bottom>scrollTop)&&(top<(scrollTop+windowHeight))){$img.css('transform',"translate3D(-50%,"+parallax+"px, 0)");}}
$this.children("img").one("load",function(){updateParallax(true);}).each(function(){if(this.complete)$(this).trigger("load");});$(window).scroll(function(){window_width=$(window).width();updateParallax(false);});$(window).resize(function(){window_width=$(window).width();updateParallax(false);});});};$('.parallax').parallax();(function(){if(!String.prototype.trim){(function(){var rtrim=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g;String.prototype.trim=function(){return this.replace(rtrim,'');};})();}
[].slice.call(document.querySelectorAll('.input__field')).forEach(function(inputEl){if(inputEl.value.trim()!==''){classie.add(inputEl.parentNode,'input--filled');}
inputEl.addEventListener('focus',onInputFocus);inputEl.addEventListener('blur',onInputBlur);});function onInputFocus(ev){classie.add(ev.target.parentNode,'input--filled');}
function onInputBlur(ev){if(ev.target.value.trim()===''){classie.remove(ev.target.parentNode,'input--filled');}}})();}};})(jQuery,Drupal);